// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNWE0ovPgOT8We9QMOk-1QzEdb91A8cxo',
    appId: '1:433362119797:web:a8f0ebb70d242f395b5c3c',
    messagingSenderId: '433362119797',
    projectId: 'flashchat-6c100',
    authDomain: 'flashchat-6c100.firebaseapp.com',
    storageBucket: 'flashchat-6c100.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKXiWt2D9jtUW5ifgo1Us9UPygCDXi69g',
    appId: '1:433362119797:android:d107abd8ba864e515b5c3c',
    messagingSenderId: '433362119797',
    projectId: 'flashchat-6c100',
    storageBucket: 'flashchat-6c100.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZRuw5POa7DQAssO6JSamwymgyKrMBMzU',
    appId: '1:433362119797:ios:6ddc5f139873270a5b5c3c',
    messagingSenderId: '433362119797',
    projectId: 'flashchat-6c100',
    storageBucket: 'flashchat-6c100.firebasestorage.app',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZRuw5POa7DQAssO6JSamwymgyKrMBMzU',
    appId: '1:433362119797:ios:6ddc5f139873270a5b5c3c',
    messagingSenderId: '433362119797',
    projectId: 'flashchat-6c100',
    storageBucket: 'flashchat-6c100.firebasestorage.app',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNWE0ovPgOT8We9QMOk-1QzEdb91A8cxo',
    appId: '1:433362119797:web:689b14957ab1e6ba5b5c3c',
    messagingSenderId: '433362119797',
    projectId: 'flashchat-6c100',
    authDomain: 'flashchat-6c100.firebaseapp.com',
    storageBucket: 'flashchat-6c100.firebasestorage.app',
  );
}
